--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (6bc9ef8)
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pse; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA pse;


--
-- Name: shared; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA shared;


--
-- Name: update_timestamp(); Type: FUNCTION; Schema: shared; Owner: -
--

CREATE FUNCTION shared.update_timestamp() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: avaliacoes_acuidade_visual; Type: TABLE; Schema: pse; Owner: -
--

CREATE TABLE pse.avaliacoes_acuidade_visual (
    id integer NOT NULL,
    aluno_id integer NOT NULL,
    escola_id integer,
    profissional_id integer,
    usf_id integer,
    avaliado_em date NOT NULL,
    ano_referencia integer NOT NULL,
    olho_direito numeric(3,2),
    olho_esquerdo numeric(3,2),
    olho_direito_reteste numeric(3,2),
    olho_esquerdo_reteste numeric(3,2),
    tem_problema_od boolean,
    tem_problema_oe boolean,
    observacoes text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: TABLE avaliacoes_acuidade_visual; Type: COMMENT; Schema: pse; Owner: -
--

COMMENT ON TABLE pse.avaliacoes_acuidade_visual IS 'Registro de avaliações de acuidade visual';


--
-- Name: COLUMN avaliacoes_acuidade_visual.tem_problema_od; Type: COMMENT; Schema: pse; Owner: -
--

COMMENT ON COLUMN pse.avaliacoes_acuidade_visual.tem_problema_od IS 'TRUE se olho_direito <= 0.60';


--
-- Name: COLUMN avaliacoes_acuidade_visual.tem_problema_oe; Type: COMMENT; Schema: pse; Owner: -
--

COMMENT ON COLUMN pse.avaliacoes_acuidade_visual.tem_problema_oe IS 'TRUE se olho_esquerdo <= 0.60';


--
-- Name: avaliacoes_acuidade_visual_id_seq; Type: SEQUENCE; Schema: pse; Owner: -
--

ALTER TABLE pse.avaliacoes_acuidade_visual ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME pse.avaliacoes_acuidade_visual_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: avaliacoes_antropometricas; Type: TABLE; Schema: pse; Owner: -
--

CREATE TABLE pse.avaliacoes_antropometricas (
    id integer NOT NULL,
    aluno_id integer NOT NULL,
    escola_id integer,
    profissional_id integer,
    usf_id integer,
    avaliado_em date NOT NULL,
    ano_referencia integer NOT NULL,
    peso_kg numeric(5,2) NOT NULL,
    altura_cm numeric(5,2) NOT NULL,
    data_nascimento date NOT NULL,
    sexo character(1) NOT NULL,
    imc numeric(5,2),
    classificacao_cdc character varying(30),
    observacoes text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: avaliacoes_antropometricas_id_seq; Type: SEQUENCE; Schema: pse; Owner: -
--

ALTER TABLE pse.avaliacoes_antropometricas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME pse.avaliacoes_antropometricas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: avaliacoes_odontologicas; Type: TABLE; Schema: pse; Owner: -
--

CREATE TABLE pse.avaliacoes_odontologicas (
    id integer NOT NULL,
    aluno_id integer NOT NULL,
    escola_id integer,
    profissional_id integer,
    usf_id integer,
    avaliado_em date NOT NULL,
    ano_referencia integer NOT NULL,
    risco character(1) NOT NULL,
    complemento character(1),
    classificacao_completa character varying(3),
    precisa_art boolean DEFAULT false,
    recebeu_atf boolean DEFAULT false,
    observacoes text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    qtde_dentes_art integer DEFAULT 0
);


--
-- Name: TABLE avaliacoes_odontologicas; Type: COMMENT; Schema: pse; Owner: -
--

COMMENT ON TABLE pse.avaliacoes_odontologicas IS 'Registro de avaliações odontológicas';


--
-- Name: COLUMN avaliacoes_odontologicas.risco; Type: COMMENT; Schema: pse; Owner: -
--

COMMENT ON COLUMN pse.avaliacoes_odontologicas.risco IS 'Classificação de risco: A, B, C, D, E, F, G';


--
-- Name: COLUMN avaliacoes_odontologicas.complemento; Type: COMMENT; Schema: pse; Owner: -
--

COMMENT ON COLUMN pse.avaliacoes_odontologicas.complemento IS 'Complemento: + ou -';


--
-- Name: COLUMN avaliacoes_odontologicas.precisa_art; Type: COMMENT; Schema: pse; Owner: -
--

COMMENT ON COLUMN pse.avaliacoes_odontologicas.precisa_art IS 'Indica se o aluno necessita de tratamento ART (Tratamento Restaurador Atraumático)';


--
-- Name: COLUMN avaliacoes_odontologicas.recebeu_atf; Type: COMMENT; Schema: pse; Owner: -
--

COMMENT ON COLUMN pse.avaliacoes_odontologicas.recebeu_atf IS 'Aplicação Tópica de Flúor';


--
-- Name: COLUMN avaliacoes_odontologicas.qtde_dentes_art; Type: COMMENT; Schema: pse; Owner: -
--

COMMENT ON COLUMN pse.avaliacoes_odontologicas.qtde_dentes_art IS 'Quantidade de dentes que podem receber tratamento ART';


--
-- Name: avaliacoes_odontologicas_id_seq; Type: SEQUENCE; Schema: pse; Owner: -
--

ALTER TABLE pse.avaliacoes_odontologicas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME pse.avaliacoes_odontologicas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: avaliadores; Type: TABLE; Schema: pse; Owner: -
--

CREATE TABLE pse.avaliadores (
    id integer NOT NULL,
    profissional_id integer NOT NULL,
    usf_id integer NOT NULL,
    is_ativo boolean DEFAULT true,
    data_entrada date DEFAULT CURRENT_DATE,
    data_saida date,
    observacoes text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: avaliadores_id_seq; Type: SEQUENCE; Schema: pse; Owner: -
--

ALTER TABLE pse.avaliadores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME pse.avaliadores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matriculas; Type: TABLE; Schema: pse; Owner: -
--

CREATE TABLE pse.matriculas (
    id integer NOT NULL,
    aluno_id integer NOT NULL,
    escola_id integer NOT NULL,
    ano_letivo integer NOT NULL,
    turma character varying(50) NOT NULL,
    periodo character varying(20) NOT NULL,
    observacoes text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: TABLE matriculas; Type: COMMENT; Schema: pse; Owner: -
--

COMMENT ON TABLE pse.matriculas IS 'Matrícula de alunos em turmas/escolas por ano letivo (simplificada - sem controle de status/datas)';


--
-- Name: COLUMN matriculas.periodo; Type: COMMENT; Schema: pse; Owner: -
--

COMMENT ON COLUMN pse.matriculas.periodo IS 'Valores aceitos: MANHÃ, TARDE, NOITE, INTEGRAL';


--
-- Name: COLUMN matriculas.observacoes; Type: COMMENT; Schema: pse; Owner: -
--

COMMENT ON COLUMN pse.matriculas.observacoes IS 'Usar para registrar transferências ou casos especiais';


--
-- Name: matriculas_id_seq; Type: SEQUENCE; Schema: pse; Owner: -
--

ALTER TABLE pse.matriculas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME pse.matriculas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sessions; Type: TABLE; Schema: pse; Owner: -
--

CREATE TABLE pse.sessions (
    id character varying(255) NOT NULL,
    profissional_id integer NOT NULL,
    email character varying(255) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: sessoes_escovacao; Type: TABLE; Schema: pse; Owner: -
--

CREATE TABLE pse.sessoes_escovacao (
    id integer NOT NULL,
    escola_id integer NOT NULL,
    turma character varying(50) NOT NULL,
    profissional_id integer,
    usf_id integer,
    data_sessao date NOT NULL,
    ano_referencia integer NOT NULL,
    total_participantes integer NOT NULL,
    observacoes text,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: TABLE sessoes_escovacao; Type: COMMENT; Schema: pse; Owner: -
--

COMMENT ON TABLE pse.sessoes_escovacao IS 'Registro de sessões de escovação orientada por turma';


--
-- Name: COLUMN sessoes_escovacao.total_participantes; Type: COMMENT; Schema: pse; Owner: -
--

COMMENT ON COLUMN pse.sessoes_escovacao.total_participantes IS 'Quantidade de alunos que participaram da sessão';


--
-- Name: sessoes_escovacao_id_seq; Type: SEQUENCE; Schema: pse; Owner: -
--

ALTER TABLE pse.sessoes_escovacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME pse.sessoes_escovacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usf_escolas; Type: TABLE; Schema: pse; Owner: -
--

CREATE TABLE pse.usf_escolas (
    id integer NOT NULL,
    usf_id integer NOT NULL,
    escola_id integer NOT NULL,
    is_ativo boolean DEFAULT true,
    data_vinculo date DEFAULT CURRENT_DATE,
    data_desvinculo date,
    observacoes text,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: usf_escolas_id_seq; Type: SEQUENCE; Schema: pse; Owner: -
--

ALTER TABLE pse.usf_escolas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME pse.usf_escolas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cep_enderecos; Type: TABLE; Schema: shared; Owner: -
--

CREATE TABLE shared.cep_enderecos (
    id integer NOT NULL,
    cep character(8) NOT NULL,
    logradouro character varying(200) NOT NULL,
    numeracao_ate character varying(100),
    bairro character varying(100) NOT NULL,
    municipio character varying(100) NOT NULL,
    uf character(2) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: cid10_completo; Type: TABLE; Schema: shared; Owner: -
--

CREATE TABLE shared.cid10_completo (
    id integer NOT NULL,
    codigo character varying(10) NOT NULL,
    codigo_sem_ponto character varying(10),
    classificacao character varying(1),
    restricao_sexo character varying(1),
    causa_obito character varying(1),
    descricao text NOT NULL,
    descricao_abreviada character varying(255),
    referencia text,
    excluidos text,
    data_importacao timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    tipo character varying(20),
    tamanho_codigo integer,
    codigo_pai character varying(10),
    numero_capitulo integer
);


--
-- Name: TABLE cid10_completo; Type: COMMENT; Schema: shared; Owner: -
--

COMMENT ON TABLE shared.cid10_completo IS 'CID-10 completo - Subcategorias (códigos com 4 caracteres)';


--
-- Name: COLUMN cid10_completo.codigo; Type: COMMENT; Schema: shared; Owner: -
--

COMMENT ON COLUMN shared.cid10_completo.codigo IS 'Código formatado com ponto (ex: A00.1)';


--
-- Name: COLUMN cid10_completo.codigo_sem_ponto; Type: COMMENT; Schema: shared; Owner: -
--

COMMENT ON COLUMN shared.cid10_completo.codigo_sem_ponto IS 'Código original do DATASUS sem ponto (ex: A001)';


--
-- Name: COLUMN cid10_completo.classificacao; Type: COMMENT; Schema: shared; Owner: -
--

COMMENT ON COLUMN shared.cid10_completo.classificacao IS 'Cruz/Asterisco: + = etiologia, * = manifestação';


--
-- Name: COLUMN cid10_completo.restricao_sexo; Type: COMMENT; Schema: shared; Owner: -
--

COMMENT ON COLUMN shared.cid10_completo.restricao_sexo IS 'F = feminino, M = masculino, NULL = ambos';


--
-- Name: COLUMN cid10_completo.causa_obito; Type: COMMENT; Schema: shared; Owner: -
--

COMMENT ON COLUMN shared.cid10_completo.causa_obito IS 'N = não causa óbito, NULL = pode causar';


--
-- Name: COLUMN cid10_completo.referencia; Type: COMMENT; Schema: shared; Owner: -
--

COMMENT ON COLUMN shared.cid10_completo.referencia IS 'Referência cruzada para códigos relacionados';


--
-- Name: COLUMN cid10_completo.excluidos; Type: COMMENT; Schema: shared; Owner: -
--

COMMENT ON COLUMN shared.cid10_completo.excluidos IS 'Códigos excluídos desta categoria';


--
-- Name: clientes; Type: TABLE; Schema: shared; Owner: -
--

CREATE TABLE shared.clientes (
    id integer NOT NULL,
    cliente character varying(200) NOT NULL,
    data_nasc date,
    sexo character(1),
    cpf character(11),
    fone character varying(11),
    cep character(8),
    logradouro character varying(150),
    numero character varying(10),
    complemento character varying(50),
    bairro character varying(100),
    municipio character varying(100) DEFAULT 'Atibaia'::character varying,
    uf character(2) DEFAULT 'SP'::bpchar,
    nome_responsavel character varying(200),
    fone_responsavel character varying(11),
    observacoes text,
    ra character(10),
    cns character(15),
    ativo boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: clientes_id_seq; Type: SEQUENCE; Schema: shared; Owner: -
--

ALTER TABLE shared.clientes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME shared.clientes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: escolas; Type: TABLE; Schema: shared; Owner: -
--

CREATE TABLE shared.escolas (
    inep integer,
    escola text,
    nome_educacao text,
    tipo text,
    usf_cnes integer,
    logradouro text,
    numero text,
    bairro text,
    cep text,
    municipio text,
    uf text,
    localizacao text,
    latitude numeric,
    longitude numeric,
    mapa text,
    fone text,
    contato text,
    email text,
    ativo text
);


--
-- Name: estabelecimentos; Type: TABLE; Schema: shared; Owner: -
--

CREATE TABLE shared.estabelecimentos (
    id integer NOT NULL,
    estabelecimento character varying(200) NOT NULL,
    nome_oficial character varying(200) NOT NULL,
    tipo_estabelecimento character varying(10) NOT NULL,
    cnes integer,
    logradouro character varying(200) NOT NULL,
    numero character varying(20) NOT NULL,
    complemento character varying(100),
    bairro character varying(100) NOT NULL,
    cep character(8),
    municipio character varying(100) DEFAULT 'Atibaia'::character varying NOT NULL,
    uf character(2) DEFAULT 'SP'::bpchar NOT NULL,
    latitude numeric(10,7),
    longitude numeric(10,7),
    ativo boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: profissionais; Type: TABLE; Schema: shared; Owner: -
--

CREATE TABLE shared.profissionais (
    id integer NOT NULL,
    nome_profissional character varying(255) NOT NULL,
    data_nasc date,
    sexo character(1),
    cpf character varying(11),
    matricula character varying(15),
    fone character varying(11),
    conta_google character varying(40),
    observacoes text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: TABLE profissionais; Type: COMMENT; Schema: shared; Owner: -
--

COMMENT ON TABLE shared.profissionais IS 'Todos os profissionais de saúde do município. Campo is_ativo_pse identifica quem pode acessar o PSE';


--
-- Name: COLUMN profissionais.conta_google; Type: COMMENT; Schema: shared; Owner: -
--

COMMENT ON COLUMN shared.profissionais.conta_google IS 'E-mail Google usado para autenticação OAuth';


--
-- Name: profissionais_id_seq; Type: SEQUENCE; Schema: shared; Owner: -
--

ALTER TABLE shared.profissionais ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME shared.profissionais_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: avaliacoes_acuidade_visual avaliacoes_acuidade_visual_pkey; Type: CONSTRAINT; Schema: pse; Owner: -
--

ALTER TABLE ONLY pse.avaliacoes_acuidade_visual
    ADD CONSTRAINT avaliacoes_acuidade_visual_pkey PRIMARY KEY (id);


--
-- Name: avaliacoes_antropometricas avaliacoes_antropometricas_pkey; Type: CONSTRAINT; Schema: pse; Owner: -
--

ALTER TABLE ONLY pse.avaliacoes_antropometricas
    ADD CONSTRAINT avaliacoes_antropometricas_pkey PRIMARY KEY (id);


--
-- Name: avaliacoes_odontologicas avaliacoes_odontologicas_pkey; Type: CONSTRAINT; Schema: pse; Owner: -
--

ALTER TABLE ONLY pse.avaliacoes_odontologicas
    ADD CONSTRAINT avaliacoes_odontologicas_pkey PRIMARY KEY (id);


--
-- Name: avaliadores avaliadores_pkey; Type: CONSTRAINT; Schema: pse; Owner: -
--

ALTER TABLE ONLY pse.avaliadores
    ADD CONSTRAINT avaliadores_pkey PRIMARY KEY (id);


--
-- Name: matriculas matriculas_pkey; Type: CONSTRAINT; Schema: pse; Owner: -
--

ALTER TABLE ONLY pse.matriculas
    ADD CONSTRAINT matriculas_pkey PRIMARY KEY (id);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: pse; Owner: -
--

ALTER TABLE ONLY pse.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- Name: sessoes_escovacao sessoes_escovacao_pkey; Type: CONSTRAINT; Schema: pse; Owner: -
--

ALTER TABLE ONLY pse.sessoes_escovacao
    ADD CONSTRAINT sessoes_escovacao_pkey PRIMARY KEY (id);


--
-- Name: usf_escolas usf_escolas_pkey; Type: CONSTRAINT; Schema: pse; Owner: -
--

ALTER TABLE ONLY pse.usf_escolas
    ADD CONSTRAINT usf_escolas_pkey PRIMARY KEY (id);


--
-- Name: cep_enderecos cep_enderecos_pkey; Type: CONSTRAINT; Schema: shared; Owner: -
--

ALTER TABLE ONLY shared.cep_enderecos
    ADD CONSTRAINT cep_enderecos_pkey PRIMARY KEY (id);


--
-- Name: cid10_completo cid10_completo_pkey; Type: CONSTRAINT; Schema: shared; Owner: -
--

ALTER TABLE ONLY shared.cid10_completo
    ADD CONSTRAINT cid10_completo_pkey PRIMARY KEY (id);


--
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: shared; Owner: -
--

ALTER TABLE ONLY shared.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (id);


--
-- Name: clientes clientes_ra_key; Type: CONSTRAINT; Schema: shared; Owner: -
--

ALTER TABLE ONLY shared.clientes
    ADD CONSTRAINT clientes_ra_key UNIQUE (ra);


--
-- Name: estabelecimentos estabelecimentos_pkey; Type: CONSTRAINT; Schema: shared; Owner: -
--

ALTER TABLE ONLY shared.estabelecimentos
    ADD CONSTRAINT estabelecimentos_pkey PRIMARY KEY (id);


--
-- Name: profissionais profissionais_pkey; Type: CONSTRAINT; Schema: shared; Owner: -
--

ALTER TABLE ONLY shared.profissionais
    ADD CONSTRAINT profissionais_pkey PRIMARY KEY (id);


--
-- Name: idx_acuidade_aluno; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_acuidade_aluno ON pse.avaliacoes_acuidade_visual USING btree (aluno_id);


--
-- Name: idx_acuidade_data; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_acuidade_data ON pse.avaliacoes_acuidade_visual USING btree (avaliado_em);


--
-- Name: idx_acuidade_escola_ano; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_acuidade_escola_ano ON pse.avaliacoes_acuidade_visual USING btree (escola_id, ano_referencia);


--
-- Name: idx_acuidade_problemas; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_acuidade_problemas ON pse.avaliacoes_acuidade_visual USING btree (tem_problema_od, tem_problema_oe);


--
-- Name: idx_acuidade_profissional; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_acuidade_profissional ON pse.avaliacoes_acuidade_visual USING btree (profissional_id);


--
-- Name: idx_avaliadores_ativo; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_avaliadores_ativo ON pse.avaliadores USING btree (is_ativo) WHERE (is_ativo = true);


--
-- Name: idx_avaliadores_profissional; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_avaliadores_profissional ON pse.avaliadores USING btree (profissional_id);


--
-- Name: idx_avaliadores_profissional_ativo; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_avaliadores_profissional_ativo ON pse.avaliadores USING btree (profissional_id, is_ativo) WHERE (is_ativo = true);


--
-- Name: idx_avaliadores_usf; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_avaliadores_usf ON pse.avaliadores USING btree (usf_id);


--
-- Name: idx_escovacao_data; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_escovacao_data ON pse.sessoes_escovacao USING btree (data_sessao);


--
-- Name: idx_escovacao_escola_ano; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_escovacao_escola_ano ON pse.sessoes_escovacao USING btree (escola_id, ano_referencia);


--
-- Name: idx_escovacao_profissional; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_escovacao_profissional ON pse.sessoes_escovacao USING btree (profissional_id);


--
-- Name: idx_escovacao_turma; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_escovacao_turma ON pse.sessoes_escovacao USING btree (turma);


--
-- Name: idx_matriculas_aluno_ano; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_matriculas_aluno_ano ON pse.matriculas USING btree (aluno_id, ano_letivo);


--
-- Name: idx_matriculas_escola_ano; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_matriculas_escola_ano ON pse.matriculas USING btree (escola_id, ano_letivo);


--
-- Name: idx_matriculas_filtro_operacional; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_matriculas_filtro_operacional ON pse.matriculas USING btree (escola_id, ano_letivo, periodo);


--
-- Name: idx_matriculas_periodo; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_matriculas_periodo ON pse.matriculas USING btree (periodo);


--
-- Name: idx_matriculas_turma; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_matriculas_turma ON pse.matriculas USING btree (turma);


--
-- Name: idx_odonto_aluno; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_odonto_aluno ON pse.avaliacoes_odontologicas USING btree (aluno_id);


--
-- Name: idx_odonto_classificacao; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_odonto_classificacao ON pse.avaliacoes_odontologicas USING btree (classificacao_completa);


--
-- Name: idx_odonto_data; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_odonto_data ON pse.avaliacoes_odontologicas USING btree (avaliado_em);


--
-- Name: idx_odonto_escola_ano; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_odonto_escola_ano ON pse.avaliacoes_odontologicas USING btree (escola_id, ano_referencia);


--
-- Name: idx_odonto_procedimentos; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_odonto_procedimentos ON pse.avaliacoes_odontologicas USING btree (precisa_art, recebeu_atf);


--
-- Name: idx_odonto_profissional; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_odonto_profissional ON pse.avaliacoes_odontologicas USING btree (profissional_id);


--
-- Name: idx_odonto_risco; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_odonto_risco ON pse.avaliacoes_odontologicas USING btree (risco);


--
-- Name: idx_usf_escolas_ativo; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_usf_escolas_ativo ON pse.usf_escolas USING btree (is_ativo) WHERE (is_ativo = true);


--
-- Name: idx_usf_escolas_escola; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_usf_escolas_escola ON pse.usf_escolas USING btree (escola_id);


--
-- Name: idx_usf_escolas_usf; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_usf_escolas_usf ON pse.usf_escolas USING btree (usf_id);


--
-- Name: idx_usf_escolas_usf_ativo; Type: INDEX; Schema: pse; Owner: -
--

CREATE INDEX idx_usf_escolas_usf_ativo ON pse.usf_escolas USING btree (usf_id, is_ativo) WHERE (is_ativo = true);


--
-- Name: uidx_avaliadores_profissional_usf_ativo; Type: INDEX; Schema: pse; Owner: -
--

CREATE UNIQUE INDEX uidx_avaliadores_profissional_usf_ativo ON pse.avaliadores USING btree (profissional_id, usf_id) WHERE (is_ativo = true);


--
-- Name: uidx_usf_escolas_usf_escola_ativo; Type: INDEX; Schema: pse; Owner: -
--

CREATE UNIQUE INDEX uidx_usf_escolas_usf_escola_ativo ON pse.usf_escolas USING btree (usf_id, escola_id) WHERE (is_ativo = true);


--
-- Name: cep_unico; Type: INDEX; Schema: shared; Owner: -
--

CREATE UNIQUE INDEX cep_unico ON shared.cep_enderecos USING btree (cep);


--
-- Name: cid10_subcategorias_codigo_key; Type: INDEX; Schema: shared; Owner: -
--

CREATE UNIQUE INDEX cid10_subcategorias_codigo_key ON shared.cid10_completo USING btree (codigo);


--
-- Name: cid10_subcategorias_pkey; Type: INDEX; Schema: shared; Owner: -
--

CREATE UNIQUE INDEX cid10_subcategorias_pkey ON shared.cid10_completo USING btree (id);


--
-- Name: clientes_cpf_key; Type: INDEX; Schema: shared; Owner: -
--

CREATE UNIQUE INDEX clientes_cpf_key ON shared.clientes USING btree (cpf);


--
-- Name: cnes_unico; Type: INDEX; Schema: shared; Owner: -
--

CREATE UNIQUE INDEX cnes_unico ON shared.estabelecimentos USING btree (cnes);


--
-- Name: idx_cid10_classificacao; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_cid10_classificacao ON shared.cid10_completo USING btree (classificacao) WHERE (classificacao IS NOT NULL);


--
-- Name: idx_cid10_codigo; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_cid10_codigo ON shared.cid10_completo USING btree (codigo);


--
-- Name: idx_cid10_codigo_sem_ponto; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_cid10_codigo_sem_ponto ON shared.cid10_completo USING btree (codigo_sem_ponto);


--
-- Name: idx_cid10_completo_codigo; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_cid10_completo_codigo ON shared.cid10_completo USING btree (codigo);


--
-- Name: idx_cid10_completo_codigo_pai; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_cid10_completo_codigo_pai ON shared.cid10_completo USING btree (codigo_pai) WHERE (codigo_pai IS NOT NULL);


--
-- Name: idx_cid10_completo_codigo_sem_ponto; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_cid10_completo_codigo_sem_ponto ON shared.cid10_completo USING btree (codigo_sem_ponto);


--
-- Name: idx_cid10_completo_descricao_busca; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_cid10_completo_descricao_busca ON shared.cid10_completo USING gin (to_tsvector('portuguese'::regconfig, descricao));


--
-- Name: idx_cid10_completo_tipo; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_cid10_completo_tipo ON shared.cid10_completo USING btree (tipo);


--
-- Name: idx_cid10_descricao; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_cid10_descricao ON shared.cid10_completo USING gin (to_tsvector('portuguese'::regconfig, descricao));


--
-- Name: idx_cid10_sexo; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_cid10_sexo ON shared.cid10_completo USING btree (restricao_sexo) WHERE (restricao_sexo IS NOT NULL);


--
-- Name: idx_cid_busca_texto; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_cid_busca_texto ON shared.cid10_completo USING gin (to_tsvector('portuguese'::regconfig, descricao));


--
-- Name: idx_cid_codigo; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_cid_codigo ON shared.cid10_completo USING btree (codigo);


--
-- Name: idx_cid_pai; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_cid_pai ON shared.cid10_completo USING btree (codigo_pai) WHERE (codigo_pai IS NOT NULL);


--
-- Name: idx_cid_sem_ponto; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_cid_sem_ponto ON shared.cid10_completo USING btree (codigo_sem_ponto);


--
-- Name: idx_cid_tipo; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_cid_tipo ON shared.cid10_completo USING btree (tipo);


--
-- Name: idx_estab_ativo; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_estab_ativo ON shared.estabelecimentos USING btree (ativo) WHERE (ativo = true);


--
-- Name: idx_estab_bairro; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_estab_bairro ON shared.estabelecimentos USING btree (bairro);


--
-- Name: idx_estab_cep; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_estab_cep ON shared.estabelecimentos USING btree (cep) WHERE (cep IS NOT NULL);


--
-- Name: idx_estab_cnes; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_estab_cnes ON shared.estabelecimentos USING btree (cnes) WHERE (cnes IS NOT NULL);


--
-- Name: idx_estab_municipio; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_estab_municipio ON shared.estabelecimentos USING btree (municipio);


--
-- Name: idx_estab_tipo; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_estab_tipo ON shared.estabelecimentos USING btree (tipo_estabelecimento);


--
-- Name: idx_estab_uf; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_estab_uf ON shared.estabelecimentos USING btree (uf);


--
-- Name: idx_profissionais_conta; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_profissionais_conta ON shared.profissionais USING btree (conta_google);


--
-- Name: idx_profissionais_cpf; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_profissionais_cpf ON shared.profissionais USING btree (cpf);


--
-- Name: idx_profissionais_nome; Type: INDEX; Schema: shared; Owner: -
--

CREATE INDEX idx_profissionais_nome ON shared.profissionais USING btree (nome_profissional);


--
-- Name: estabelecimentos fk_cep; Type: FK CONSTRAINT; Schema: shared; Owner: -
--

ALTER TABLE ONLY shared.estabelecimentos
    ADD CONSTRAINT fk_cep FOREIGN KEY (cep) REFERENCES shared.cep_enderecos(cep) ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

